### ISSUE TITLE
Waves are moving the wrong direction

### ISSUE THREAD

**Issue by nivs1978** [jno6809/jc_reborn#1]
I noticed the waves are moving away from the island, and not towards the island. The order the waves are played, should be reversed.

**Comment by xesf** [comment]
Nice catch Hans ;)

**Comment by jno6809** [comment]
Hi Hans and Alexandre ;)
Well observed.
But I think you observed the island while it was low tide. In that case, the waves do move away from it, while they move towards when high tide.
This is faithful to the original (I just checked it), as far as I observed. So I'm going to close this issue, but don't hesitate in opening any other if needed.
