### ISSUE TITLE
NULL palette error

### ISSUE THREAD

**Issue by maxolasersquad** [jno6809/jc_reborn#12]
When I run the application I get this result.

```sh
$ ls
jc_reborn     RESOURCE.MAP  sound10.wav  sound14.wav  sound16.wav  sound18.wav  sound1.wav   sound21.wav  sound23.wav  sound2.wav  sound4.wav  sound6.wav  sound8.wav
RESOURCE.001  sound0.wav    sound12.wav  sound15.wav  sound17.wav  sound19.wav  sound20.wav  sound22.wav  sound24.wav  sound3.wav  sound5.wav  sound7.wav  sound9.wav
$ ./jc_reborn 


 Fatal error : NULL palette


$
```

**Comment by Crim** [comment]
I had this error when I had a bad copy of the RESOURCE.MAP and RESOURCE.001 files.  Try the "pre-installed" copy of the game?

**Comment by xesf** [comment]
What version of Johnny Castaway are you using? 1.00 or 1.01?

What OS and arch?

**Comment by xesf** [comment]
Make sure to use the de-compressed versions of the files after setup installation.
