### ISSUE TITLE
Link for original resource files?

### ISSUE THREAD

**Issue by Spishak** [jno6809/jc_reborn#13]
Anyone have a working link to the original resource files?

Not able to find them, and trying to compile with files with a different md5 doesnt work.

Thanks!

**Comment by xesf** [comment]
It is copyrighted material so I won't add the link, but any download ready for DosBox should work.
Make sure you have the installed version, not the compressed files before the setup.

It should work with both versions 1.00 and 1.01, although if I remember correctly the PR I did for dumping the wavs inly works for version 1.01 which is the most available version out there.

**Comment by xesf** [comment]
Closing as copyright material won't be linked but easily found on the web.
