### ISSUE TITLE
Stretched full screen on composite on raspberry pi

### ISSUE THREAD

**Issue by hvogelpohl** [jno6809/jc_reborn#8]
Hi,

I know, this feels odd, but I struggle to get it scaled to borderless full screen on a raspberry pi zero. I'm running composite, that means fixed 720x* and so i get a thick black border on the right side of the screen which i cannot get rid of. I tried to mess around with overlays etc. and still no success. Maybe it's because the whole app is runnning in preprocessor width 640, but i don't know.

apart from this it's running really great! I'm using it for this project: [https://www.thingiverse.com/thing:3328477](https://www.thingiverse.com/thing:3328477)

Do you know what I can do?

**Comment by 8bitbubsy** [comment]
Hi,

The program is running in 632x400 (Yes, not 640x400). Original FT2 runs in 640x400, but not the clone.
Anyway, you should be able to fix this by enabling "Stretched" in Configuration -> Miscellaneous. If this doesn't work, then I'm out of ideas.

Btw, does it play XMs without problems on a Pi Zero? That's quite a slow device...

**Comment by hvogelpohl** [comment]
Hi,

i start this app from bash without running any desktop. In that case, pi zero would be way too slow. I think that there is no way to handle recaling when in fullscreen mode.

I think i'll apply a _hardware_ overlay to cover the black part on the right.

**Comment by 8bitbubsy** [comment]
Haha I'm sorry, I managed to actually comment on a project that isn't mine. I got the notification so I thought it was about my own program. I'm still a beginner to this GitHub stuff.

**Comment by nivs1978** [comment]
The original screen saver was fixed to 640x480 pixel resolution. It was made before wide screens. So best option is if you can run that resolution have have you monitor stretch this to fill, if you want to avoid the black borders.

**Comment by xesf** [comment]
Closing as native resolution only supports 4x3 squared resolutions and not wide 16x9.
